spring:
    # ========================================= 【mysql数据库配置】 ====================================================
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/zb_server?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
        username: root
        password:
        maxWait: 60000
        minIdle: 1
    jackson:
        time-zone: GMT+8
        date-format: yyyy-MM-dd HH:mm:ss

     #============================================oracle数据库配置=====================================================#
    secondary:
       datasource:
         names: ds1
         ds1:
           driverClassName: oracle.jdbc.driver.OracleDriver
           url: jdbc:oracle:thin:@127.0.0.1:1521:orcl
           username: ems
           password: ems

  third:
       datasource:
         names: ds2
         ds2:
           driverClassName: org.postgresql.Driver
           url: jdbc:postgresql://127.0.0.1:5432/sims
           username: root
           password: root
    # ========================================= 【activemq消息队列配置】 ===============================================
    activemq:
      brokerUrl: failover\:(tcp\://192.168.19.129\:51511,tcp\://192.168.19.129\:51512,tcp\://192.168.19.129\:51513)?randomize=false
      user: admin
      password: admin
      packages:
        trustAll: true
      pool:
        enabled: false

    # ========================================= 【dubbo配置】 ==========================================================
    dubbo:
      protocol:
        host: 192.168.1.128
        port: 20880 # 通信端口；在同一台机器上，这个端口号不能与其他服务提供者的端口号有重复的；你也可以不配置，dubbo会默认给你分配；
        name: rmi #协议
      application: sea-center-service-user # dubbo应用名称
      registry:
        address: zookeeper://192.168.19.129:2181?backup=192.168.19.129:2182,192.168.19.129:2183 # zookeeper注册中心地址
        #address: zookeeper://127.0.0.1:2180 # zookeeper注册中心地址
        timeout: 30000 # 接口调用超时时间，默认50000
        check: false # 项目启动时，检查注册中心是否可用（是否启动了zookeeper注册中心）
      provider:
        retries: 0 # 重试次数，0表示不重试

    # ========================================= 【activiti工作流配置】 =================================================
    activiti:
      # activiti工作流在项目启动过程中，会检查resources目录下是否存在processes目录并且目录下有bpmn工作流文件；
      #     如果检查到没有processes目录或者processes目录为空，则会抛异常：java.io.FileNotFoundException: class path resource [processes/] cannot be resolved to URL because it does not exist
      # 【处理办法】：
      #           1、在resource目录下添加processes文件夹，并且文件夹不能为空，必须有文件存在；可以随意加入一个文件即可，比如：bpmn、txt等文件，文件类型不限制
      #           2、通过配置check-process-definitions: false，关闭activiti启动时候的检查
      check-process-definitions: false  # 如果设置为true，当processes目录下有bpmn工作流文件的时候，会自动进行部署到mysql数据库的activiti对应的表中

    # ========================================= 【redis缓存配置】 =================================================
#    redis:
#      database: 0   # Redis数据库索引（默认为0）
#      host: 127.0.0.1   # redis服务器地址
#      password:    #redis密码
#      port: 6379  # 端口号
#      pool:
#        max-idle: 10     # 连接池中的最大空闲连接
#        min-idle: 0      # 连接池中的最小空闲连接
#        max-wait: 1000   # 连接池最大阻塞等待时间（使用负值表示没有限制）
#        max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
#      timeout: 2000       # 连接超时时间 单位 ms（毫秒）

#====================================redis集群版=================================================#
    redis:
        nodes: 192.168.19.129:7001,192.168.19.129:7003,192.168.19.129:7005
        commandTimeout: 2000
        password:    #redis密码

# ========================================= 【mysql从库配置】 ==========================================================
    custom:
      datasource:
          type: com.alibaba.druid.pool.DruidDataSource
          driverClassName: com.mysql.jdbc.Driver
          url: jdbc:mysql://127.0.0.1:3306/zb_server?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
          username: root
          password:
      jackson:
          time-zone: GMT+8
          date-format: yyyy-MM-dd HH:mm:ss
#=================================================solr===============================================================
    data:
      solr:
        zk-host: 192.168.19.129:2181,192.168.19.129:2182,192.168.19.129:2183
      mongodb:
        uri: mongodb://192.168.19.129:27017/zb_server
#================================activemq================================================#
activemq:
    user: admin
    password: admin
    broker-url: failover\:(tcp\://192.168.19.129\:51511,tcp\://192.168.19.129\:51512,tcp\://192.168.19.129\:51513)?jms.prefetchPolicy.queuePrefetch=50&jms.redeliveryPolicy.maximumRedeliveries=1&randomize=false&initialReconnectDelay=1000&maxReconnectDelay=30000
    pool:
      enabled: true
      max-connections: 10

queueName: sxx.queue
topicName: sxx.topic


#===============================================jpa===================================================#
jpa:
  database: mysql
  show-sql: true
  hibernate.ddl-auto: update
  properties:
    hibernate:
      dialect: org.hibernate.dialect.MySQL5Dialect


