
# ################## 这个yml配置文件，你可以理解成是一个通用的配置；比如dev、pro不同环境的配置，都继承此文件中的配置；##################
# ################## 项目启动的时候，默认会加载此yml文件，根据profiles的环境配置，再加载对应的application-dev(pro).yml的配置文件；##################

server:
  port: 8081  # 设置80端口
  tomcat:
    uri-encoding: utf-8

# 查看springboot开启了哪些配置
debug: false

# 不同开发环境的配置
# logback-spring.xml中的配置也会根据不同环境的配置，实现不同的日志输出
spring:
  profiles:
    active: dev

#    logs: ./elasticsearch/log #elasticsearch日志存储目录
#    data: ./elasticsearch/data #elasticsearch数据存储目录

# mybatis配置
# mybatis-plus 优化
mybatis-plus:
  mapper-locations: classpath:mybatis/**/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.ruoyi.service
  #typeEnumsPackage: com.baomidou.springboot.entity.enums
  global-config:
    # 数据库相关配置
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: id_worker
      #字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
      field-strategy: not_empty
      #驼峰下划线转换
      column-underline: true
      #数据库大写下划线转换
      #capital-mode: true
      #逻辑删除配置
      logic-delete-value: 0
      logic-not-delete-value: 1
      db-type: h2
    #刷新mapper 调试神器
    refresh: true
  # 原生配置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false

mapper:
    identity: MYSQL # 指定数据库方言，默认mysql；如果是mysql数据库的话，这里也可以不用配置
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql






